"""
data.py -- clean loaders for BCI Competition IV Dataset 1 and Dataset 2a.

Written fresh for the v3 redesign. Two deliberate departures from the
repository's `datasets_io.py`:

  * ds2a uses the **documented** motor-imagery window (2.0, 6.0) s relative to
    trial onset. The repo's driver silently used (0.5, 4.5), which covers 1.5 s
    of fixation plus the cue-evoked response plus only ~1.5 s of imagery.
    See AUDIT_2026-07-29.md finding A3.
  * Epoching returns *unfiltered* epochs; every consumer band-passes for
    itself, so no method can accidentally be handed broadband data while
    another gets an optimised pass-band (audit finding A1).
"""
from __future__ import annotations

from pathlib import Path
from typing import Tuple, List

import numpy as np
import scipy.io as sio

# --------------------------------------------------------------------------- #
# Dataset 1  (BCICIV_calib_ds1*.mat)
# --------------------------------------------------------------------------- #
# Subjects a, b, f, g are recorded from human subjects.
# Subjects c, d, e are ARTIFICIALLY GENERATED by the competition organisers.
DS1_REAL = ["a", "b", "f", "g"]
DS1_ARTIFICIAL = ["c", "d", "e"]
DS1_ALL = ["a", "b", "c", "d", "e", "f", "g"]


def load_ds1(dataset_dir, subject: str,
             window: Tuple[float, float] = (0.5, 4.0)) -> dict:
    """
    Load one Dataset 1 calibration subject.

    Returns dict with X (trials, channels, samples), y (0/1), fs, ch_names.

    The calibration files are 100 Hz, 59 channels, 200 cued trials,
    two classes drawn per subject from {left hand, right hand, foot}.
    Cue onset is at `mrk.pos`; the imagery period is 4 s. We take
    (0.5, 4.0) s to skip the cue-evoked transient -- a fixed choice made
    before any test data was touched.
    """
    path = Path(dataset_dir) / f"BCICIV_calib_ds1{subject}.mat"
    if not path.exists():
        raise FileNotFoundError(f"[ds1] missing {path}")
    m = sio.loadmat(str(path))

    # cnt is int16 scaled by 0.1 uV per the dataset description.
    cnt = m["cnt"].astype(np.float64) * 0.1          # (samples, channels)
    nfo = m["nfo"]
    fs = int(np.asarray(nfo["fs"][0, 0]).ravel()[0])
    ch_names = [str(c[0]) for c in np.asarray(nfo["clab"][0, 0]).ravel()]
    classes = [str(np.asarray(c).ravel()[0])
               for c in np.asarray(nfo["classes"][0, 0]).ravel()]

    mrk = m["mrk"]
    pos = np.asarray(mrk["pos"][0, 0]).ravel().astype(int)
    ycue = np.asarray(mrk["y"][0, 0]).ravel().astype(int)   # -1 / +1

    X, y = _epoch(cnt, pos, (ycue > 0).astype(int), fs, window)
    return dict(X=X, y=y, fs=fs, ch_names=ch_names,
                class_names=classes, dataset="ds1", subject=subject)


# --------------------------------------------------------------------------- #
# Dataset 2a  (A0?T.mat, the BBCI/Kaggle `data` cell export)
# --------------------------------------------------------------------------- #
DS2A_ALL = [1, 2, 3, 4, 5, 6, 7, 8, 9]
_DS2A_CLASS_NAMES = ["left_hand", "right_hand", "feet", "tongue"]


def load_ds2a(dataset_dir, subject: int, variant: str = "binary",
              session: str = "T",
              window: Tuple[float, float] = (2.0, 6.0),
              drop_artifacts: bool = False) -> dict:
    """
    Load one Dataset 2a subject.

    `window` is seconds relative to the value in the `trial` field, which
    marks FIXATION onset. The cue appears at ~2 s and imagery runs ~3-6 s,
    so (2.0, 6.0) is the standard 4 s motor-imagery period.

    variant: 'binary' -> left vs right hand (classes 1,2) as labels 0/1
             '4class' -> all four classes as labels 0..3
    """
    path = Path(dataset_dir) / f"A0{int(subject)}{session}.mat"
    if not path.exists():
        raise FileNotFoundError(f"[ds2a] missing {path}")
    m = sio.loadmat(str(path))
    runs = m["data"]

    Xs, ys = [], []
    fs = None
    for i in range(runs.shape[1]):
        r = runs[0, i]
        try:
            sig = np.asarray(r["X"][0, 0], dtype=np.float64)
            trial = np.asarray(r["trial"][0, 0]).ravel().astype(int)
            lab = np.asarray(r["y"][0, 0]).ravel().astype(int)
            rfs = int(np.asarray(r["fs"][0, 0]).ravel()[0])
            art = np.asarray(r["artifacts"][0, 0]).ravel().astype(int)
        except Exception:
            continue
        # The first runs of 2a are eye-movement / baseline recordings with no
        # MI trials; they carry 0 trials or no labels.
        if trial.size == 0 or lab.size == 0 or lab.max() == 0:
            continue
        fs = rfs
        # Drop the 3 EOG channels, keep 22 EEG.
        sig = sig[:, :22]
        # A handful of 2a exports carry NaNs at run boundaries.
        if np.isnan(sig).any():
            sig = np.nan_to_num(sig, nan=0.0)
        Xr, yr = _epoch(sig, trial, lab - 1, rfs, window)
        if drop_artifacts and art.size == lab.size:
            keep = art[: len(yr)] == 0
            Xr, yr = Xr[keep], yr[keep]
        Xs.append(Xr)
        ys.append(yr)

    if not Xs:
        raise ValueError(f"[ds2a] no MI runs found in {path}")
    X = np.concatenate(Xs, axis=0)
    y = np.concatenate(ys, axis=0)

    if variant == "binary":
        keep = np.isin(y, [0, 1])
        X, y = X[keep], y[keep].astype(int)
        class_names = _DS2A_CLASS_NAMES[:2]
    elif variant == "4class":
        class_names = list(_DS2A_CLASS_NAMES)
    else:
        raise ValueError(f"unknown variant {variant!r}")

    ch_names = [f"EEG{i+1}" for i in range(X.shape[1])]
    return dict(X=X, y=y, fs=fs, ch_names=ch_names,
                class_names=class_names, dataset=f"ds2a_{variant}",
                subject=int(subject))


# --------------------------------------------------------------------------- #
def _epoch(sig: np.ndarray, onsets: np.ndarray, labels: np.ndarray,
           fs: int, window: Tuple[float, float]):
    """
    sig: (samples, channels). Returns (trials, channels, samples), labels.
    Trials whose window falls outside the recording are dropped, and the
    number dropped is reported by the caller via the shape difference.
    """
    a = int(round(window[0] * fs))
    b = int(round(window[1] * fs))
    n = b - a
    out, lab = [], []
    for o, l in zip(onsets, labels):
        s, e = o + a, o + b
        if s >= 0 and e <= sig.shape[0]:
            out.append(sig[s:e, :].T)
            lab.append(l)
    if not out:
        raise ValueError("no valid epochs -- check window/onsets")
    return np.asarray(out, dtype=np.float64), np.asarray(lab, dtype=int)


def load_unit(dataset: str, dataset_dir, subject) -> dict:
    """Dispatch used by the runner."""
    if dataset == "ds1":
        return load_ds1(dataset_dir, str(subject))
    if dataset == "ds2a_binary":
        return load_ds2a(dataset_dir, int(subject), variant="binary")
    if dataset == "ds2a_4class":
        return load_ds2a(dataset_dir, int(subject), variant="4class")
    raise ValueError(f"unknown dataset {dataset!r}")


def subjects_for(dataset: str) -> List:
    if dataset == "ds1":
        return list(DS1_ALL)
    return list(DS2A_ALL)
