"""
protocol.py -- the pre-registered confirmatory evaluation.

The pre-registration below is frozen BEFORE the confirmatory run. Everything
that could be chosen to flatter the proposed method -- datasets, subjects,
seeds, split fractions, baselines, metric, unit of analysis, statistical test,
multiplicity correction, and the success criterion -- is fixed here in code and
written verbatim to `preregistration.json` at the start of the run.

The run is executed once. Results are appended per unit and never regenerated.
"""
from __future__ import annotations

import json
import logging
import os
import sys
import time
import traceback
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence

import numpy as np

import baselines_v3 as B
import data as D
import pipeline as P

# =========================================================================== #
#                            PRE-REGISTRATION
# =========================================================================== #
PREREG = {
    "title": "Confirmatory evaluation of ARTS against corrected baselines",
    "frozen": "2026-07-29",

    "datasets": {
        "ds1": {
            "subjects": D.DS1_ALL,
            "note": "BCI IV Dataset 1. Subjects c,d,e are ARTIFICIALLY "
                    "GENERATED by the competition organisers and are reported "
                    "separately in the per-subject table. The primary ds1 "
                    "analysis is pre-specified on ALL SEVEN; a secondary "
                    "analysis on the four real subjects (a,b,f,g) is also "
                    "pre-specified because the artificial subjects are near "
                    "ceiling and could mask a difference.",
            "classes": "two per subject, but NOT the same two for every "
                       "subject (a,f = left/foot; b,c,d,e,g = left/right). "
                       "Cross-subject transfer is therefore restricted to "
                       "source subjects sharing the target's class pair.",
            "window_s": [0.5, 4.0],
        },
        "ds2a_binary": {
            "subjects": D.DS2A_ALL,
            "window_s": [2.0, 6.0],
            "note": "Left vs right hand. Window is the standard 4 s MI period "
                    "beginning 2 s after fixation onset. The repository used "
                    "(0.5,4.5), which is mostly fixation and cue.",
        },
        "ds2a_4class": {
            "subjects": D.DS2A_ALL,
            "window_s": [2.0, 6.0],
            "note": "Pre-specified as a secondary confirmatory analysis: it "
                    "has twice the trials, so it is the better-powered test.",
        },
    },

    "seeds": [42, 43, 44, 45, 46, 47, 48, 49, 50, 51],

    "split": {
        "scheme": "stratified train/test, single split per (subject, seed)",
        "test_fraction": 0.30,
        "note": "Raised from the repository's 0.15. With 22-30 test trials an "
                "exact McNemar test essentially cannot reach p<0.05, so the "
                "repository's 95% tie rate was partly mechanical (audit B3).",
        "validation": "Methods requiring model selection carve 20% of their "
                      "OWN training portion. No method sees more data than "
                      "another (audit B2).",
    },

    "methods": {
        "ARTS": "proposed: 6-band Riemannian tangent-space views, Euclidean "
                "alignment, per-source-subject transfer views on 8-30 Hz, "
                "out-of-fold stacked logistic fusion",
        "riemannian_ts": "B4 corrected: 8-30 Hz, OAS, EA, tangent space, L2 LR",
        "fbcsp": "B5: filter-bank CSP + mutual-information selection + LDA",
        "eegnet": "B6 corrected: 4-38 Hz input, max-norm, early stopping",
        "single_best": "B1: best single CSP pool member, selected on inner val",
        "random_search": "B2: 300-draw budgeted random search over the same "
                         "ensemble space, selected on inner val",
        "dag_sa": "B3: the published method with its search bugs fixed",
    },

    "primary_metric": "accuracy",
    "secondary_metrics": ["cohen_kappa", "balanced_accuracy",
                          "per_class_precision_recall_f1"],

    "unit_of_analysis": {
        "primary": "subject",
        "rationale": "Seeds are re-splits of the same trials, so seed-level "
                     "replicates are not independent and a CI over seeds "
                     "measures split noise, not generalisation to a new "
                     "subject (audit A4). Accuracy is averaged over the 10 "
                     "seeds within a subject first; the CI is then taken "
                     "across subjects with a t critical value on n-1 df.",
        "secondary": "(subject, seed) unit, for the paired McNemar analysis",
    },

    "statistical_test": {
        "test": "exact two-sided McNemar, paired on identical test trials",
        "applied_at": "each (subject, seed) unit",
        "multiplicity": "Holm-Bonferroni within each (proposed vs baseline) "
                        "comparison across its units",
        "gate": "a unit counts as a win/loss only if its Holm-corrected "
                "p < 0.05; otherwise it is a tie",
        "paired_ci": "paired t interval on the per-subject differences",
    },

    "success_criterion": {
        "primary": "On a given dataset, ARTS is declared superior only if, "
                   "against EVERY baseline, the lower bound of the 95% paired "
                   "CI on the per-subject accuracy difference is > 0 AND the "
                   "point estimate is >= 2.0 accuracy points.",
        "equivalence": "A difference whose 95% CI lies entirely within "
                       "+/- 2.0 points is reported as a TIE, not a win.",
        "indeterminate": "Anything else is reported as inconclusive at this "
                         "sample size, with the CI given.",
        "no_post_hoc": "No baseline, subject, seed or metric may be dropped "
                       "after seeing results. The table is reported in full.",
    },

    "development_disclosure": [
        "Method design used ONLY cross-validation inside the training "
        "portion, at development seeds 900-902, which are disjoint from the "
        "confirmatory seeds 42-51.",
        "Two exceptions are disclosed: (a) a label-permutation leakage check "
        "on ds1 subject a scored held-out folds at seeds 0-4; (b) "
        "`reference_check.py` scored 5-fold CV for textbook CSP+LDA and "
        "tangent-space baselines on both datasets at seed 0. Both were "
        "diagnostics on baselines, not tuning of ARTS, but they did inform "
        "the judgement that the manuscript's accuracy LEVEL is a "
        "preprocessing artefact.",
        "Frozen ARTS hyperparameters: 6 bands (4-8, 8-12, 12-16, 16-22, "
        "22-30, 8-30 Hz); C_self=C_src=0.1; C_meta=1.0; 5 inner folds; "
        "per-source-subject transfer views on the 8-30 Hz band only.",
    ],
}


# =========================================================================== #
#                                 RUNNER
# =========================================================================== #
@dataclass
class RunCfg:
    ds1_dir: str = ""
    ds2a_dir: str = ""
    out_dir: str = "results_v3"
    datasets: Sequence[str] = ("ds1", "ds2a_binary", "ds2a_4class")
    seeds: Sequence[int] = tuple(PREREG["seeds"])
    test_fraction: float = 0.30
    run_eegnet: bool = True
    run_ablation: bool = True


ARTS_FROZEN = P.ARTSConfig(
    bands=P.DEFAULT_BANDS,
    use_alignment=True,
    use_transfer=True,
    src_mode="per_subject",
    src_bands=(P.RIEMANNIAN_BASELINE_BAND,),
    use_csp=False,
    fusion="stack",
    C_self=0.1, C_src=0.1, C_meta=1.0,
)

# The ablation ladder. Each row differs from the row above by ONE component,
# so the attribution of any gain is unambiguous.
ABLATION = {
    "A0_single_band":  P.ARTSConfig(bands=(P.RIEMANNIAN_BASELINE_BAND,),
                                    use_transfer=False, fusion="mean"),
    "A1_filterbank_mean": P.ARTSConfig(use_transfer=False, fusion="mean"),
    "A2_filterbank_stack": P.ARTSConfig(use_transfer=False, fusion="stack"),
    "A3_no_alignment": P.ARTSConfig(use_transfer=False, fusion="stack",
                                    use_alignment=False),
    "A4_transfer_pooled": P.ARTSConfig(src_mode="pooled"),
    "A5_full": ARTS_FROZEN,
}


def setup_logging(out_dir: Path):
    out_dir.mkdir(parents=True, exist_ok=True)
    log = logging.getLogger("v3")
    log.setLevel(logging.INFO)
    log.handlers.clear()
    fh = logging.FileHandler(out_dir / "run.log")
    sh = logging.StreamHandler(sys.stdout)
    fmt = logging.Formatter("%(asctime)s %(levelname)s %(message)s")
    for h in (fh, sh):
        h.setFormatter(fmt)
        log.addHandler(h)
    return log


def _load_all(dataset: str, cfg: RunCfg, log):
    """
    Load every subject of a dataset and precompute band covariances.

    Covariances are cached to disk. They depend only on the raw recording, the
    epoch window and the band definitions -- never on a split, a seed or a
    label -- so caching them cannot leak anything, and it makes a resumed run
    start in seconds instead of minutes.
    """
    d = cfg.ds1_dir if dataset == "ds1" else cfg.ds2a_dir
    cache_dir = Path(cfg.out_dir) / "cov_cache"
    cache_dir.mkdir(parents=True, exist_ok=True)
    units, raw = {}, {}
    for s in D.subjects_for(dataset):
        u = D.load_unit(dataset, d, s)
        raw[s] = u
        cp = cache_dir / f"{dataset}_{s}.npz"
        bands = list(P.DEFAULT_BANDS) + [b for b in B.FBCSP_BANDS
                                         if b not in P.DEFAULT_BANDS]
        if cp.exists():
            z = np.load(cp, allow_pickle=False)
            covs = {bands[i]: z[f"b{i}"] for i in range(len(bands))}
            units[s] = P.SubjectBands(covs=covs, y=z["y"], subject=s)
        else:
            units[s] = P.SubjectBands.build(u["X"], u["y"], u["fs"], s,
                                            bands=bands)
            np.savez_compressed(
                cp, y=units[s].y,
                **{f"b{i}": units[s].covs[b] for i, b in enumerate(bands)})
        log.info(f"  loaded {dataset} subject {s}: X={u['X'].shape} "
                 f"classes={u['class_names']}")
    return units, raw


def _sources_for(dataset, s, units, raw):
    """
    Source subjects for transfer.

    Dataset 1's class pair differs by subject, so a source subject is only
    usable if its two classes are the SAME two classes as the target's.
    Ignoring this asks a source model to map 'foot' and 'right hand' onto the
    same output, which is why pooled transfer was worthless on ds1 in
    development.
    """
    out = []
    for o in units:
        if o == s:
            continue
        if dataset == "ds1" and raw[o]["class_names"] != raw[s]["class_names"]:
            continue
        out.append(units[o])
    return out


def run(cfg: RunCfg):
    out = Path(cfg.out_dir)
    log = setup_logging(out)
    (out / "preregistration.json").write_text(json.dumps(PREREG, indent=2))
    (out / "run_config.json").write_text(json.dumps(asdict(cfg), indent=2))
    log.info("pre-registration written; beginning confirmatory run")

    pred_path = out / "predictions.jsonl"
    done = set()
    if pred_path.exists():
        for line in pred_path.read_text().splitlines():
            if line.strip():
                r = json.loads(line)
                done.add((r["dataset"], str(r["subject"]), r["seed"]))
        log.info(f"resuming: {len(done)} units already complete")

    have_torch = cfg.run_eegnet and B.eegnet_available()
    if cfg.run_eegnet and not have_torch:
        log.warning("torch unavailable -- EEGNet will be recorded as SKIPPED, "
                    "not silently omitted")

    for dataset in cfg.datasets:
        log.info(f"=== dataset {dataset} ===")
        units, raw = _load_all(dataset, cfg, log)
        # Source models depend only on other subjects' data, never on the
        # target's split, so they are fitted once per target and reused for
        # every seed and every ablation row that shares their configuration.
        src_cache: Dict = {}

        for s in D.subjects_for(dataset):
            tb = units[s]
            srcs = _sources_for(dataset, s, units, raw)
            for seed in cfg.seeds:
                key = (dataset, str(s), seed)
                if key in done:
                    continue
                t0 = time.time()
                try:
                    rec = _run_unit(dataset, s, seed, tb, srcs, raw[s], cfg,
                                    src_cache, have_torch, log)
                except Exception as e:
                    log.error(f"unit {key} FAILED: {e}\n{traceback.format_exc()}")
                    continue
                rec["secs"] = round(time.time() - t0, 1)
                with open(pred_path, "a") as f:
                    f.write(json.dumps(rec) + "\n")
                    f.flush()
                    os.fsync(f.fileno())
                log.info(f"  {dataset} s={s} seed={seed} done in "
                         f"{rec['secs']}s :: " +
                         "  ".join(f"{k}={np.mean(np.array(v)==np.array(rec['y_true'])):.3f}"
                                   for k, v in rec["pred"].items()
                                   if v is not None))
        del units, raw, src_cache
    log.info("run complete")


def _run_unit(dataset, s, seed, tb, srcs, rawu, cfg, src_cache, have_torch,
              log):
    from sklearn.model_selection import train_test_split
    y = tb.y
    idx = np.arange(len(y))
    tr, te = train_test_split(idx, test_size=cfg.test_fraction,
                              random_state=seed, stratify=y)
    tr, te = np.sort(tr), np.sort(te)

    rec = {"dataset": dataset, "subject": s, "seed": seed,
           "y_true": y[te].tolist(), "test_idx": te.tolist(),
           "class_names": rawu["class_names"], "pred": {}, "notes": {}}

    # ---- proposed method + ablation ladder --------------------------- #
    rows = {"ARTS": ARTS_FROZEN}
    if cfg.run_ablation:
        rows.update(ABLATION)
    feat_cache: Dict = {}      # shared across configs, dropped after the unit
    for name, acfg in rows.items():
        m = P.ARTS(acfg, seed=seed, feature_cache=feat_cache)
        if acfg.use_transfer and srcs:
            ck = (str(s), acfg.src_mode, tuple(acfg.src_bands or acfg.bands),
                  acfg.use_alignment, acfg.C_src)
            if ck not in src_cache:
                m0 = P.ARTS(acfg, seed=seed).fit_sources(srcs)
                if acfg.src_mode == "per_subject":
                    m0.fit_sources_per_subject(srcs, acfg.src_bands)
                src_cache[ck] = (m0._src_models, getattr(m0, "_src_per", {}))
            m._src_models, m._src_per = src_cache[ck]
        elif acfg.use_transfer and not srcs:
            # ds1 subjects whose class pair is unique have no usable source.
            rec["notes"][name] = "no class-matched source subjects"
            m._src_models = {}
        m.fit(tb, tr, srcs)
        rec["pred"][name] = m.predict(tb, te).tolist()
        if name == "ARTS":
            rec["notes"]["n_views"] = len(m.view_names_)
            rec["notes"]["view_names"] = m.view_names_

    # ---- baselines --------------------------------------------------- #
    rec["pred"]["riemannian_ts"] = B.riemannian_ts(tb, tr, te, seed).tolist()
    rec["pred"]["fbcsp"] = B.fbcsp(tb, tr, te, seed).tolist()

    pool = B.build_pool(tb, tr, seed)
    rec["notes"]["pool_size"] = len(pool)
    rec["pred"]["single_best"] = B.single_best(tb, tr, te, pool, seed).tolist()
    rec["pred"]["random_search"] = B.random_search(tb, tr, te, pool,
                                                   seed).tolist()
    rec["pred"]["dag_sa"] = B.dag_sa(tb, tr, te, pool, seed).tolist()

    if have_torch:
        try:
            rec["pred"]["eegnet"] = B.eegnet(
                rawu["X"], y, tr, te, rawu["fs"], seed).tolist()
        except Exception as e:
            rec["pred"]["eegnet"] = None
            rec["notes"]["eegnet_error"] = str(e)
            log.error(f"EEGNet failed on {dataset} s={s} seed={seed}: {e}")
    else:
        rec["pred"]["eegnet"] = None
        rec["notes"]["eegnet"] = "SKIPPED (torch unavailable)"
    return rec
